#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod pool;
pub mod registry;
pub mod staking;
pub mod swap_erc20;
pub mod wrapper;
