#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod i_pool;
pub mod i_registry;
pub mod i_staking;
pub mod i_swap_erc20;
pub mod i_wrapper;
